apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hw-container
        image: 1ds22cs141/app1-k8s:latest
        ports:
        - containerPort: 5000
#kubectl apply -f deployment.yaml
#kubectl apply -f service.yaml
# kubectl get pods
#kubectl get svc
# kubectl scale deployment/hw-deployment --replicas=3
#kubectl get deployment
#kubectl get pods
#kubectl port-forward svc/hello-world 5000:5000

#access through http://localhost:5000/
